### ISSUE TITLE
[Config] Pass controllers in bootstrapOptions

### ISSUE THREAD

**Issue by Jaze23** [L2jLiga/fastify-decorators#11]
Hi, this package is really nice !

I think it would be awesome if we could pass directly the controller classes we want inside the bootstrapOptions like this for example :

```ts
const bootstrapOptions = {
    //  The controllers we actually want to load
    controllers: [
       UsersController,
       TodosController,
       ...
    ],
};
```
That way we could pass down the controllers to fastify-decorators without necessarily knowing where they are and just treat them as "modules".

Let me know what you think :)

Thanks !

**Comment by L2jLiga** [comment]
Sounds pretty cool!
I honestly think about such approach. It has several benefits:
- allows to avoid FS operations (find/load all files with Controllers) hence it's fully-compatible with ES2015+ modules
- allows to do not use `export default` statement since we directly pass classes to bootstrap
- something I missed

**Comment by L2jLiga** [comment]
Hi There!
Sorry for long silence, I've implemented this functionality and going to publish as `2.0.0-7`.
Please check-out [documentation](https://github.com/L2jLiga/fastify-decorators/blob/next/lib/docs/Controllers.md#bootstrap-controllers)

Cheers!
