### ISSUE TITLE
Fastify decorates don't have any response

### ISSUE THREAD

**Issue by teachdugsimt** [L2jLiga/fastify-decorators#286]
I work with aws lambda - apigateway.
In normal fastify anything work correctly but in fastify-decorators It don't have any response.
I can see log in cloudwatch : "Final data :  []" but apigateway don't have response {message:'test reply'}. It has only "Internal server error"  that no object:{message: { type: 'string' }}

```import { FastifyReply, FastifyRequest, FastifyInstance, FastifySchema } from 'fastify';
import { Controller, GET, getInstanceByToken, FastifyInstanceToken } from 'fastify-decorators';
import PingService from '../services/ping.service';

@Controller({ route: '/api/v1/truck' })
export default class PingController {

  public static instance: FastifyInstance = getInstanceByToken(FastifyInstanceToken);
  private pingService = getInstanceByToken<PingService>(PingService);

  @GET({
    url: '/mobile',
    options: {
      schema: <FastifySchema>{
        tags: ['messageController'],
        response: {
          200: {
            type: 'object',
            properties: {
              message: { type: 'string' }
            },
          }
        },
      },
    },
  })
  async pingHandler(req: FastifyRequest, reply: FastifyReply): Promise<any> {
    try {
      const data = await this.pingService?.ping(PingController.instance, null)
      console.log("Final data : ", JSON.parse(JSON.stringify(data)))
      // reply.status(200).send({ message: 'test reply' })
      // reply.send({ message: 'test reply' })
      return reply.status(200).send({ message: 'test reply' })
      //   return { message: 'test reply' }
    } catch (err) {
      console.log("Errorr : ", err)
      throw err
    }

  }

}```


"fastify-decorators": "^3.9.1"

**Comment by L2jLiga** [comment]
Hi @teachdugsimt, the issue is return statement, you are trying to mix  `async/await` and `reply.send`.

If you would like to use `reply.send` then ensure that method resolves with undefined (no return statement at all), also you can just return object and it will work.

You can read about this behavior here: https://github.com/fastify/fastify/blob/main/docs/Routes.md#async-await

**Comment by teachdugsimt** [comment]
> Hi @teachdugsimt, the issue is return statement, you are trying to mix `async/await` and `reply.send`.
> 
> If you would like to use `reply.send` then ensure that method resolves with undefined (no return statement at all), also you can just return object and it will work.
> 
> You can read about this behavior here: https://github.com/fastify/fastify/blob/main/docs/Routes.md#async-await

Oh so sorry. In. main handler I forget insert callback function. In here

```
const awsLambdaFastify = require('aws-lambda-fastify');
const app = require('./dist/server');
const proxy = awsLambdaFastify(app);

exports.handler = (event, context, callback) => { // here
  context.callbackWaitsForEmptyEventLoop = false;
  proxy(event, context, callback);   // and here
};

```

**Comment by L2jLiga** [comment]
Honestly, I didn't work with AWS lambda at all. It will take time to understand what and why went wrong. However if you will find out way to solve this - please left some notes about :)

**Comment by L2jLiga** [comment]
Hi @teachdugsimt,

I've just created an example of how to use AWS lambda with Fastify and it works as expected for me, you can check it here:
https://github.com/L2jLiga/fastify-decorators/tree/v3/examples/aws-lambda

One note: to build working version example need to be copied outside of library due to some problems how Vercel proceed files in Lerna monorepo, after that it works as expected
