### ISSUE TITLE
How do use instance inside a decorator?

### ISSUE THREAD

**Issue by kgoedecke** [L2jLiga/fastify-decorators#760]
Hi @L2jLiga ☺️

I found those outdated doc: https://github.com/L2jLiga/fastify-decorators/blob/ce557da3ad59722f5a6755610890287bfeef0f51/lib/docs/Controllers.md#accessing-fastifyinstance-in-decorators

Is this still the way to do this, I can't seem to make it work to access the instance to add it as a `preHandler`

Here's what I want to achieve: https://github.com/fastify/fastify-bearer-auth#integration-with-fastifyauth

**Comment by L2jLiga** [comment]
Hi Kevin =)

Injecting FastifyInstance in decorators is actually quite tricky, this is due to how stuff are loaded.

In general all decorators are executed just as normal functions when file required/imported and there's two ways how it can be done:
1. via import statement
2. via autoloader

in first case decorators will be executed before FastifyInstance can be injected, in second option FastifyInstance will be already available when decorators are executed.

More or less best suitable workaround is to use lambda in combination with `@Inject` decorator:

```typescript
@Controller('/foo')
class Foo {
  @Inject(FastifyInstanceToken) declare static instance: FastifyInstance;

  @GET({
      url: '',
      options: {
          preValidation: (req, res, next) => MyController.instance.preValidationDecorator(req, res, next)
      }
  })
  public async validatedRoute() {
      /* Some stuff */
  }
}
```

**Comment by kgoedecke** [comment]
I've managed to got it working with this:

```js
preHandler: ((
      request: FastifyRequest,
      reply: FastifyReply,
      done: () => void,
    ) => {
      if (request.server.verifyBearerAuth) request.server.verifyBearerAuth(request, reply, done);
      done();
    }) as preHandlerHookHandler,
```
is there any reason to not do it in that way? I couldn't make it work with your suggested code.

**Comment by L2jLiga** [comment]
I don't see any reasons to don't do it such way, probably simplify it a bit only
`request.server.verifyBearerAuth?.(request, reply, next)`

And in case when this preValidation should be applied for all routes inside controller it's better to use `@Hook` instead

**Comment by L2jLiga** [comment]
It seems you solved your issue, closing for now
