### ISSUE TITLE
@fastify-decorators/typedi published with cjs?

### ISSUE THREAD

**Issue by gustavopedroni** [L2jLiga/fastify-decorators#836]
Poderia gerar uma versão compativel com CommonJS do pacote @fastify-decorators/typedi? 
Infelizmente na stack atual não consigo mudar para "type": "module"

**Comment by L2jLiga** [comment]
Hi there, 
typedi support was introduced in v4 only which is ESM only, I made such decision due to issue to support several dual packages within same monorepo, especially I faced with lot of issues with Jest.
However v4 exists for long time and new major versions of jest were published, do things might change.
Right now it's possible already to use typedi for injection via classLoader API introduced in https://github.com/L2jLiga/fastify-decorators/releases/tag/v3.13.0, you can check small code snippet at https://github.com/L2jLiga/fastify-decorators/blob/v3.13.0/docs/Bootstrapping.md#using-custom-class-loader

And about plans for v4, I would like to wait for Typescript 4.9/4.10 and update docs before releasing it at latest tag, maybe I will return back dual package if it won't bring lot of problems and discount CJS in v5

**Comment by L2jLiga** [comment]
Just published [v4.0.0-next.5](https://github.com/L2jLiga/fastify-decorators/releases/tag/v4.0.0-next.5)
