### ISSUE TITLE
Cannot access [service] before initialization

### ISSUE THREAD

**Issue by niels-bosman** [L2jLiga/fastify-decorators#865]
I have two services that both have dependencies to each other:

### FileBackupsService
```ts
@Service()
export class FileBackupsService {
  constructor(
    private queueService: QueueService,
  ) {}

  // Class methods
}
```

### QueueService
```ts
@Service()
export class QueueService {
  constructor(
    private fileBackupsService: FileBackupsService,
  ) {}

  // Class methods
}
```

When trying to inject the `QueueService` into the FileBackupsService I get the following error:

```
ReferenceError: Cannot access 'QueueService' before initialization
    at file:///Users/niels/Code/work/magicul/backup-server/src/services/FileBackupsService.ts:17:27
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

What can I do to resolve this? Looks like the order of the dependency injection is not going as planned. I do need them to have dependencies to each other.

**Comment by L2jLiga** [comment]
Hi there!
This issue isn't related to library itself but related to how ECMAScript Modules works, issue happens because of cyclic dependencies which aren't supported by ESM itself, even if you manage it works with some hacks the next problem is services initialization - how to create service which depends on another service which depends on initial service?
I would consider to rethink and rework this services to avoid cyclic depending on each other by merging or creating separated service for example.

You can refer to this docs to learn more about https://angular.io/errors/NG0200. Even its for Angular, concepts are same across programming languages and frameworks

**Comment by niels-bosman** [comment]
@L2jLiga That makes sense, thanks. Closing this since it is not related to this library itself.
